# Generated by Django 6.0.5 on 2026-05-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedstatus',
            name='bed_type',
            field=models.CharField(choices=[('GENERAL', 'General Bed / Ward'), ('CABIN_STANDARD', 'Single Cabin (Standard)'), ('CABIN_DELUXE', 'Deluxe / Executive Cabin'), ('ICU', 'Intensive Care Unit (ICU)'), ('CCU', 'Coronary Care Unit (CCU)'), ('NICU', 'Neonatal ICU (NICU)')], default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='bedstatus',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
