# Generated by Django 6.0.5 on 2026-05-24 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_alter_bedstatus_bed_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedreservation',
            name='extension_count',
        ),
        migrations.AddField(
            model_name='bedreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedreservation',
            name='medical_document',
            field=models.FileField(blank=True, null=True, upload_to='medical_proofs/'),
        ),
        migrations.AlterField(
            model_name='bedreservation',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
